apiVersion: v1
kind: Service
metadata:
  name: vehicle-service-svc
  labels:
    app: vehicle-status-service
spec:
  type: NodePort
  ports:
    - name: app-port
      targetPort: 8080
      port: 8080
  selector:
    app: vehicle-status-service
